import streamlit as st
import requests
import pandas as pd

st.set_page_config(
    page_title="Enterprise Relational SQL Agent Hub",
    page_icon="📊",
    layout="wide"
)

# Render Custom Application Headers
st.title("📊 Enterprise Relational SQL Agent Hub")
st.markdown("### Pure Local AI Execution Environment")
st.caption("Driven exclusively by local FastAPI endpoints and local Ollama inference loops.")
st.markdown("---")

# Layout Split: Sidebar containing real relational blueprints
with st.sidebar:
    st.header("🗄️ Database Structural Schema")
    st.markdown("""
    Your active local `enterprise.db` architecture:
    
    1. **`users`** (Contains user footprint data)
       - `user_id` (Primary Key)
       - `customer_name` (Text)
       - `email` (Text)
       
    2. **`orders`** (Contains operational transactions)
       - `order_id` (Primary Key)
       - `user_id` (Foreign Key referencing `users.user_id`)
       - `product_name` (Text)
       - `category` (Text)
       - `total_amount` (Real)
       - `status` (Text)
    """)

# Primary Input Form Field
user_query = st.text_input(
    "Type an analytical conversational business question here:", 
    placeholder="e.g., What is the average order amount for purchases made by Carlos Santana?"
)

if user_query:
    # Dedicated loading message matching your long local CPU execution times
    with st.spinner("FastAPI Core routing request to local Ollama (Llama 3) engine... Please wait while your CPU calculates the relational mapping..."):
        try:
            # Pointing straight to your live FastAPI backend cluster port
            backend_url = "http://127.0.0.1:8000/api/ask"
            payload = {"prompt": user_query}
            
            # Send payload across local network sockets with maximized timeout threshold
            res = requests.post(backend_url, json=payload, timeout=600)
            
            if res.status_code == 200:
                data_pack = res.json()
                
                # Check if the AI backend agent caught a malicious input flag
                if data_pack.get("status") == "blocked":
                    st.error(f"🚨 Security Guardrail Alert: {data_pack.get('message')}")
                else:
                    st.success(f"🎉 Query successfully compiled and resolved by Llama 3 in {data_pack.get('attempts')} agent loop(s)!")
                    
                    # Split data presentation into clean UI tabs
                    tab1, tab2 = st.tabs(["📋 Processed Data View", "⚙️ Dynamic Agent Trace Logs"])
                    
                    with tab1:
                        raw_records = data_pack.get("data", [])
                        if raw_records:
                            # Convert JSON payload results into a DataFrame
                            df = pd.DataFrame(raw_records)
                            st.dataframe(df, use_container_width=True)
                            
                            # Automatically generate a visual bar chart if numeric columns exist
                            if len(df.columns) >= 2:
                                try:
                                    st.markdown("#### 📈 Visual Metrics Extraction")
                                    st.bar_chart(data=df, x=df.columns[0], y=df.columns[1])
                                except Exception:
                                    pass
                        else:
                            st.info("The query executed successfully, but no matching database entries were found.")
                            
                    with tab2:
                        st.subheader("Auto-Compiled SQL Query Statement")
                        st.markdown("This query string was dynamically generated by your local Ollama instance:")
                        st.code(data_pack.get("sql"), language="sql")
            else:
                st.error(f"Backend Server Error (Status Code {res.status_code}): {res.text}")
                
        except requests.exceptions.Timeout:
            st.error("❌ Execution Timeout: Ollama took more than 10 minutes to process this complex model prompt context.")
        except requests.exceptions.ConnectionError:
            st.error("❌ Connection Refused: Verify your FastAPI backend server is running via Uvicorn on port 8000.")